### ISSUE TITLE
Prompt for master password when not provided

### ISSUE THREAD

**Issue by edouard-lopez** [edouard-lopez/lesspass-powershell#20]
[Python implementation](https://github.com/lesspass/lesspass/blob/61e771bb772c3664fc757437d3e1d05a076aa873/cli/lesspass/core.py#L32-L36) request `master password` when only `site` and `login` are provided.

```
❯ lesspass "site" "login"
Master Password:
```

See [`Read-Host`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/read-host?view=powershell-5.0):
> Reads a line of input from the console.

```
$Name = Read-Host "What's your name?"
echo "Hello, $Name!"
[int]$Age = Read-Host "What's your age?"
```

**Comment by sctfic** [comment]
Prompt if not provided `[Parameter(Mandatory=$true)]`
